2015/03/09 01:03:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:03:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:03:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola
---
2015/03/09 01:03:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:05:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:05:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:05:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:07:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:07:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:08:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:08:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:09:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:09:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:09:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:09:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:10:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:11:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:14:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:14:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:14:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:31:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:31:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:32:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:32:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:32:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:32:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:32:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:34:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "asdf/asdf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('asdf/asdf')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/asdf/asdf
---
2015/03/09 01:47:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:48:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "wwe".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('wwe')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/wwe
---
2015/03/09 01:49:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "wwe".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('wwe')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('wwe')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/wwe')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/wwe
---
2015/03/09 01:49:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "wwe.php".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('wwe.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('wwe.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/wwe.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/wwe.php
---
2015/03/09 01:50:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "wwe.php".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('wwe.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('wwe.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/wwe.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/facilito/site/wwe.php
---
2015/03/09 01:56:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:57:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:57:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 01:57:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 02:18:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "home/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('home/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/home/index
---
2015/03/09 02:37:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "home/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('home/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/home/index
---
2015/03/09 02:37:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 02:40:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 02:57:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "hola/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 03:20:48 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\yii\facilito\protected\views\hola\index.php:3)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): HolaController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): HolaController->renderPartial()
#2 C:\xampp\htdocs\yii\facilito\protected\controllers\HolaController.php(9): HolaController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): HolaController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): HolaController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): HolaController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): HolaController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yii\facilito\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/facilito/hola/index
in C:\xampp\htdocs\yii\facilito\protected\views\hola\index.php (3)
in C:\xampp\htdocs\yii\facilito\protected\controllers\HolaController.php (9)
in C:\xampp\htdocs\yii\facilito\index.php (13)
2015/03/09 04:10:00 [error] [exception.CDbException] exception 'CDbException' with message 'The table "tbl_user" for active record class "Users" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 C:\xampp\htdocs\yii\facilito\protected\controllers\HolaController.php(7): CActiveRecord->findAll()
#5 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): HolaController->actionIndex()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#12 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/09 04:10:19 [error] [exception.CException] exception 'CException' with message 'Property "Users.email" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('email')
#1 C:\xampp\htdocs\yii\facilito\protected\views\hola\index.php(3): CActiveRecord->__get('email')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#6 C:\xampp\htdocs\yii\facilito\protected\controllers\HolaController.php(9): CController->render('index', Array)
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): HolaController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/14 01:34:22 [error] [exception.CDbException] exception 'CDbException' with message 'The table "tbl_user" for active record class "Users" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 C:\xampp\htdocs\yii\facilito\protected\controllers\HolaController.php(7): CActiveRecord->findAll()
#5 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): HolaController->actionIndex()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#12 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facilito/hola/index
---
2015/03/14 01:34:37 [error] [exception.CDbException] exception 'CDbException' with message 'The table "tbl_user" for active record class "Users" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 C:\xampp\htdocs\yii\facilito\protected\controllers\HolaController.php(7): CActiveRecord->findAll()
#5 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): HolaController->actionIndex()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('hola/index')
#11 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#12 C:\xampp\htdocs\yii\facilito\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/facilito/hola/index
---
